### ISSUE TITLE
Papyros-session not starting

### ISSUE THREAD

**Issue by alexkreidler** [papyros/papyros-shell#161]
After I run papyros-session it just gets stuck there and never opens anything.
This is a 64-bit ArchLinux VirtualBox system running an xfce4 desktop.
This is my first time trying to start Papyros, so I might just be making a beginner's mistake.
When I run papyros-session, the terminal prints:

```
Registered io.papyros.session D-Bus interface
papyros.session.launcher: Registered io.papyros.launcher D-Bus interface
Starting: "greenisland" "--shell io.papyros.shell"
QObject::connect: No such slot CompositorLauncher::compositorError(QProcess::ProcessError)
QObject::connect: No such slot CompositorLauncher::compositorFinished(int,QProcess::ExitStatus)
QML debugging is enabled. Only use this in a safe environment.
libEGL warning: DRI2: failed to authenticate
OS: Arch Linux [linux version 4.2.2-1-ARCH]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1
Wayland version: 1.8.1
Qt version: 5.5.0
QtCompositor version: 5.5
Green Island version: 0.6.0
Environment variables:
  XDG_VTNR=1
  QT_XCB_GL_INTEGRATION=xcb_egl
  XDG_SESSION_ID=c2
  XDG_DATA_DIRS=/usr/share:/usr/local/share:/usr/share
  XDG_CONFIG_HOME=/home/alex/.config
  QT_QPA_PLATFORMTHEME=Material
  XDG_CONFIG_DIRS=/etc/xdg:/etc/xdg:/etc/xdg
  XDG_RUNTIME_DIR=/run/user/1000
  XDG_DATA_HOME=/home/alex/.local/share
  QT_PLATFORM_PLUGIN=Material
  QSG_RENDER_LOOP=windows
  QT_WAYLAND_DISABLE_WINDOWDECORATION=1
  QT_QUICK_CONTROLS_STYLE=Material
  XDG_SEAT=seat0
  XDG_CURRENT_DESKTOP=Papyros
  XDG_MENU_PREFIX=xfce-
  QT_IM_MODULE=compose
QtCompositor: Failed to initialize EGL display. There is no EGL_WL_bind_wayland_display extension.
greenisland.protocols.wlshell.trace: GreenIsland::WlShellGlobal::WlShellGlobal(QObject*)
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShellGlobal::XdgShellGlobal(GreenIsland::Compositor*)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: GreenIsland::GtkShellGlobal::GtkShellGlobal(QObject*)
greenisland.protocols.gtkshell.trace: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.wlsubcompositor.trace: GreenIsland::WlSubCompositorGlobal::WlSubCompositorGlobal(QObject*)
greenisland.protocols.wlsubcompositor.trace: virtual const wl_interface* GreenIsland::WlSubCompositorGlobal::interface() const
greenisland.protocols.wlsubcompositor.trace: virtual const wl_interface* GreenIsland::WlSubCompositorGlobal::interface() const
greenisland.screenbackend.native: Screen added "VGA-0" QRect(0,31 1440x689)
greenisland.compositor: Added primary output "VGA-0" with geometry QRect(0,31 1440x689)
greenisland.compositor: Loading scene on output "VGA-0" QRect(0,31 1440x689)
greenisland.compositor: Loading "io.papyros.shell" shell for output "VGA-0" QRect(0,31 1440x689)
Autostart: "vboxclient" from "/etc/xdg/autostart/vboxclient.desktop"
Launching "" from "/etc/xdg/autostart/vboxclient.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/vboxclient.desktop" (vboxclient) with pid 6575
greenisland.compositor: QML scene ready
papyros.session.launcher: Application for "/etc/xdg/autostart/vboxclient.desktop" finished with exit code 0
greenisland.compositor: Scene load time: 1079 ms
greenisland.compositor: Showing window for output "VGA-0" QRect(0,31 1440x689)
QEGLPlatformContext: Failed to create context: 3004
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
```

**Comment by goodmind** [comment]
same for me too

**Comment by MarcinWieczorek** [comment]
Same. Manjaro x64, noveau drivers, using greenisland-git (hoped there would be fixes), same with greenisland pkg from AUR.

```
Registered io.papyros.session D-Bus interface
papyros.session.launcher: Registered io.papyros.launcher D-Bus interface
Starting: "greenisland" "--shell io.papyros.shell"
QObject::connect: No such slot CompositorLauncher::compositorError(QProcess::ProcessError)
QObject::connect: No such slot CompositorLauncher::compositorFinished(int,QProcess::ExitStatus)
QML debugging is enabled. Only use this in a safe environment.
libEGL warning: DRI2: failed to authenticate
OS: Manjaro Linux [linux version 4.1.13-1-MANJARO]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2
Wayland version: 1.9.0
Qt version: 5.5.1
Green Island version: 0.6.92
Environment variables:
  XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
  XDG_CONFIG_DIRS=/etc/xdg:/etc/xdg:/etc/xdg
  QT_STYLE_OVERRIDE=gtk
  XDG_DATA_HOME=/home/marcin/.local/share
  XDG_SEAT=seat0
  XDG_CONFIG_HOME=/home/marcin/.config
  XDG_DATA_DIRS=/usr/share:/usr/local/share:/usr/share
  XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
  XDG_RUNTIME_DIR=/run/user/1000
  XDG_CURRENT_DESKTOP=Papyros
  XDG_SESSION_TYPE=x11
  QSG_RENDER_LOOP=windows
  XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/marcin
  QT_QPA_PLATFORMTHEME=Material
  XDG_SESSION_DESKTOP=xfce
  QT_QUICK_CONTROLS_STYLE=Material
  XDG_MENU_PREFIX=xfce-
  QT_PLATFORM_PLUGIN=Material
  XDG_SESSION_ID=c2
  XDG_VTNR=7
  QT_XCB_GL_INTEGRATION=xcb_egl
  QT_IM_MODULE=compose
QtCompositor: Failed to initialize EGL display. There is no EGL_WL_bind_wayland_display extension.
greenisland.protocols.wlshell.trace: GreenIsland::WlShellGlobal::WlShellGlobal(QObject*)
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShellGlobal::XdgShellGlobal(GreenIsland::Compositor*)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: GreenIsland::GtkShellGlobal::GtkShellGlobal(QObject*)
greenisland.protocols.gtkshell.trace: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.screenbackend.native: Screen added "HDMI-1" QRect(0,0 1920x1052)
greenisland.compositor: Added primary output "HDMI-1" with geometry QRect(0,0 1920x1052)
greenisland.screenbackend.native: Screen added "HDMI-2" QRect(1920,0 1920x1052)
greenisland.compositor: Added  output "HDMI-2" with geometry QRect(1920,0 1920x1052)
greenisland.compositor: Loading scene on output "HDMI-1" QRect(0,0 1920x1052)
greenisland.compositor: Loading "io.papyros.shell" shell for output "HDMI-1" QRect(0,0 1920x1052)
greenisland.compositor: QML scene ready
greenisland.compositor: Scene load time: 255 ms
greenisland.compositor: Showing window for output "HDMI-1" QRect(0,0 1920x1052)
QEGLPlatformContext: Failed to create context: 3004
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
Autostart: "f.lux indicator applet" from "/home/marcin/.config/autostart/fluxgui.desktop"
Launching "" from "/home/marcin/.config/autostart/fluxgui.desktop"
papyros.session.launcher: Launched "/home/marcin/.config/autostart/fluxgui.desktop" (f.lux indicator applet) with pid 9479
Autostart: "ScreenShooter" from "/usr/share/applications/screenshooter.desktop"
Launching "" from "/usr/share/applications/screenshooter.desktop"
papyros.session.launcher: Launched "/usr/share/applications/screenshooter.desktop" (ScreenShooter) with pid 9480
Autostart: "Blueman Applet" from "/etc/xdg/autostart/blueman.desktop"
Launching "" from "/etc/xdg/autostart/blueman.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/blueman.desktop" (Blueman Applet) with pid 9481
Autostart: "Manjaro Settings Manager Daemon" from "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop"
Launching "" from "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop" (Manjaro Settings Manager Daemon) with pid 9482
Autostart: "Network" from "/etc/xdg/autostart/nm-applet.desktop"
Launching "" from "/etc/xdg/autostart/nm-applet.desktop"
Failed to create display (Connection refused)
papyros.session.launcher: Launched "/etc/xdg/autostart/nm-applet.desktop" (Network) with pid 9483
Autostart: "Pulse Audio Applet" from "/etc/xdg/autostart/pa-applet.desktop"
Launching "" from "/etc/xdg/autostart/pa-applet.desktop"
Failed to create display (Connection refused)
papyros.session.launcher: Launched "/etc/xdg/autostart/pa-applet.desktop" (Pulse Audio Applet) with pid 9486
Autostart: "Update Notifier" from "/etc/xdg/autostart/pamac-tray.desktop"
Launching "" from "/etc/xdg/autostart/pamac-tray.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/pamac-tray.desktop" (Update Notifier) with pid 9488
Autostart: "Print Queue Applet" from "/etc/xdg/autostart/print-applet.desktop"
Launching "" from "/etc/xdg/autostart/print-applet.desktop"

(nm-applet:9483): Gtk-WARNING **: cannot open display: :0.0

(pa-applet:9486): Gtk-WARNING **: cannot open display: :0.0
papyros.session.launcher: Launched "/etc/xdg/autostart/print-applet.desktop" (Print Queue Applet) with pid 9489
Autostart: "PulseAudio Sound System" from "/etc/xdg/autostart/pulseaudio.desktop"
Launching "" from "/etc/xdg/autostart/pulseaudio.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/pulseaudio.desktop" (PulseAudio Sound System) with pid 9492
Autostart: "Power Manager" from "/etc/xdg/autostart/xfce4-power-manager.desktop"
Launching "" from "/etc/xdg/autostart/xfce4-power-manager.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/xfce4-power-manager.desktop" (Power Manager) with pid 9493
Failure: Module initialization failed
fluxgui is already running, exiting
papyros.session.launcher: Application for "/usr/share/applications/screenshooter.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/nm-applet.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/pamac-tray.desktop" finished with exit code 0
papyros.session.launcher: Application for "/etc/xdg/autostart/pa-applet.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/pulseaudio.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/xfce4-power-manager.desktop" finished with exit code 0
papyros.session.launcher: Application for "/home/marcin/.config/autostart/fluxgui.desktop" finished with exit code 0
sys:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.

(blueman-applet:9481): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(blueman-applet:9481): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 120, in <module>
    BluemanApplet()
  File "/usr/bin/blueman-applet", line 51, in __init__
    setup_icon_path()
  File "/usr/lib/python3.5/site-packages/blueman/Functions.py", line 174, in setup_icon_path
    ic.prepend_search_path(ICON_PATH)
AttributeError: 'NoneType' object has no attribute 'prepend_search_path'
papyros.session.launcher: Application for "/etc/xdg/autostart/blueman.desktop" finished with exit code 1
sys:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.

```

**Comment by c0d3st0rm** [comment]
Same here too.

**Comment by iBelieve** [comment]
VirtualBox unfortunately does not support Wayland. Please see https://github.com/papyros/papyros-shell/wiki/Running-in-a-Virtual-Machine.

**Comment by MarcinWieczorek** [comment]
I was not running it on VB...
