### ISSUE TITLE
Shell crashes when opening and closing apps

### ISSUE THREAD

**Issue by alexkreidler** [papyros/papyros-shell#190]
Looks like this is the issue:
`TypeError: Cannot read property 'type' of undefined`
Full logs (the top is cut off): http://pastebin.com/w1k0F0td

**Comment by alexkreidler** [comment]
Just updated Papyros, it still crashes, but when closing apps.
Think this is the issue:
`file:///usr/lib/qt/qml/GreenIsland/Desktop/WindowManager.qml:96: Error: Cannot assign to non-existent property "transientChildren"`
I also noticed this error was apparent in the first issue.
Full logs (the top is cut off again)
http://pastebin.com/1eDA9rKv

**Comment by iBelieve** [comment]
I was able to reproduce this while running in the debugger. Here's the backtrace:

```
#0  0x00007ffff6128030 in wl_resource_get_id () from /usr/lib/libwayland-server.so.0
#1  0x00007ffff76eb971 in QWaylandSurface::ping (this=0x14c1e490)
    at /home/mspencer/Developer/papyros/greenisland/src/waylandcompositor/compositor_api/qwaylandsurface.cpp:347
#2  0x00007ffff7703755 in QWaylandSurface::qt_static_metacall (_o=_o@entry=0x14c1e490, _c=_c@entry=QMetaObject::InvokeMetaMethod, 
    _id=_id@entry=27, _a=_a@entry=0x7fffffffbb90)
    at /home/mspencer/Developer/papyros/greenisland/build/src/waylandcompositor/moc_qwaylandsurface.cpp:293
#3  0x00007ffff77046a8 in QWaylandSurface::qt_metacall (this=this@entry=0x14c1e490, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=27, 
    _a=_a@entry=0x7fffffffbb90) at /home/mspencer/Developer/papyros/greenisland/build/src/waylandcompositor/moc_qwaylandsurface.cpp:514
#4  0x00007ffff7704735 in QWaylandQuickSurface::qt_metacall (this=0x14c1e490, _c=QMetaObject::InvokeMetaMethod, _id=<optimized out>, 
    _a=0x7fffffffbb90) at /home/mspencer/Developer/papyros/greenisland/build/src/waylandcompositor/moc_qwaylandquicksurface.cpp:155
#5  0x00007ffff6bf5f69 in ?? () from /usr/lib/libQt5Qml.so.5
#6  0x00007ffff6b7494e in ?? () from /usr/lib/libQt5Qml.so.5
#7  0x00007ffff6b75805 in ?? () from /usr/lib/libQt5Qml.so.5
#8  0x00007ffff6b760cd in QV4::QObjectMethod::callInternal(QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#9  0x00007ffff6b8caa3 in QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#10 0x00007fffd53d5e32 in ?? ()
#11 0x0000000015217410 in ?? ()
#12 0x0000000000000000 in ?? ()
```

And here's some relevent logs:

```
greenisland.compositor: Surface created QWaylandQuickSurface(0x147c7040)
wl_subsurface.set_desync not implemented
greenisland.protocols.xdgshell.trace: virtual bool GreenIsland::XdgSurface::runOperation(QWaylandSurfaceOp*)
greenisland.protocols.xdgshell.trace: Run operation 1002
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShell::shell_destroy_resource(QtWaylandServer::xdg_shell::Resource*)
greenisland.protocols.xdgshell.trace: virtual GreenIsland::XdgShell::~XdgShell()
greenisland.protocols.xdgshell.trace: virtual GreenIsland::XdgSurface::~XdgSurface()
qml: Looking for window 0
qml: Application window unmapped
qml:    window: GreenIsland::ClientWindow(0x16de0210)
qml:    id: 0
qml:    surface: QWaylandQuickSurface(0x14c1e490)
qml:    appId: evince
qml:    title: Recent Documents
qml:    position: 374,102
qml:    size: 600x600
qml:    type: TopLevel
qml:    parentWindow: null
qml:    screen: eDP1
qml: Forgetting window 0
file:///usr/lib/qt/qml/GreenIsland/Desktop/WindowManager.qml:96: Error: Cannot assign to non-existent property "transientChildren"
qml: INDEX -1
file:///usr/share/greenisland/shells/io.papyros.shell/desktop/WindowSwitcher.qml:75: TypeError: Cannot read property 'item' of undefined
qml: Looking for id 0
qml: Application window destroyed
qml:    window: GreenIsland::ClientWindow(0x16de0210)
qml:    id: 0
qml:    surface: QWaylandQuickSurface(0x14c1e490)
qml:    appId: evince
qml:    title: Recent Documents
qml:    position: 374,102
qml:    size: 600x600
qml:    type: TopLevel
qml:    parentWindow: null
qml:    screen: eDP1
qml: Forgetting window 0
file:///usr/lib/qt/qml/GreenIsland/Desktop/WindowManager.qml:96: Error: Cannot assign to non-existent property "transientChildren"
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShell::shell_destroy_resource(QtWaylandServer::xdg_shell::Resource*)
greenisland.protocols.xdgshell.trace: virtual GreenIsland::XdgShell::~XdgShell()
greenisland.compositor: Surface created QWaylandQuickSurface(0xd1379f0)
greenisland.compositor: Surface created QWaylandQuickSurface(0x16be72e0)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShellGlobal::bind(wl_client*, uint32_t, uint32_t)
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShell::XdgShell(wl_client*, uint32_t, uint32_t, QObject*)
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShell::shell_use_unstable_version(QtWaylandServer::xdg_shell::Resource*, int32_t)
greenisland.compositor: Surface created QWaylandQuickSurface(0x14e841f0)
greenisland.compositor: Surface created QWaylandQuickSurface(0x166e4ff0)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShellGlobal::bind(wl_client*, uint32_t, uint32_t)
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShell::XdgShell(wl_client*, uint32_t, uint32_t, QObject*)
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShell::shell_use_unstable_version(QtWaylandServer::xdg_shell::Resource*, int32_t)
greenisland.protocols.xdgshell.trace: virtual void GreenIsland::XdgShell::shell_destroy_resource(QtWaylandServer::xdg_shell::Resource*)
greenisland.protocols.xdgshell.trace: virtual GreenIsland::XdgShell::~XdgShell()
qml: PING!
```

What I'm guessing is happening is that the window wrapper isn't getting deleted, so the ping/pong timer (used to see if a window is still responding) tries to ping the deleted window object, which then crashes the shell.
